name: Protobuf Compile
on:
  push:
    branches:
      - '*'
      - '!main'
 
jobs:
  go-image-build:
    uses:  tommzn/github-ci/.github/workflows/go.protobuf.complie.yml@v1.0.40
    secrets:
      cr-pat: ${{ secrets.PUSH_TOKEN }}
      slack-channel: ${{ secrets.SLACK_CHANNEL }}
      slack-bottoken: ${{ secrets.SLACK_BOT_TOKEN }}

  test-ci:
    name: Update Golang Events
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.ref_type: ${{ github.ref_type }}"
