name: Protobuf Deployment
on:
  create:
    tags:
      - v*
      
jobs:
  compile-go:
    uses:  tommzn/github-ci/.github/workflows/go.protobuf.complie.yml@v1.0.48
    secrets:
      cr-pat: ${{ secrets.PUSH_TOKEN }}
      slack-channel: ${{ secrets.SLACK_CHANNEL }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
    with:
      upload-artifact: true

  deploy-go:
    name: Update Golang Events
    runs-on: ubuntu-latest
    needs: compile-go
    continue-on-error: true
    env:
      GOLANG_EVENTS_REPO: ${{ secrets.TARGET_REPO }}
    steps:
      - name: Set version tag
        id: release
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\/}
      - name: Checkout Golang events lib
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GOLANG_EVENTS_REPO }}
          ref: main
      - name: Download Golang events
        uses: actions/download-artifact@v2
        with:
          name: golang-events
      - name: Check for Changes
        run: |
          git add -N .
          ! git diff --quiet
      - name: Add Changes
        if: ${{ success() }}
        env:
          USERNAME: ${{ secrets.PUSH_USER }}
          EMAIL: ${{ secrets.PUSH_EMAIL }}
        run: |
          git config --global user.name $USERNAME
          git config --global user.email $EMAIL
          git add -A
          git commit -am "Updated by $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/$GITHUB_SHA"
      - name: Update Repository
        env:
          REPO_KEY: ${{ secrets.PUSH_TOKEN }}
          USERNAME: ${{ secrets.PUSH_USER }}
          EMAIL: ${{ secrets.PUSH_EMAIL }}
        run: |
          git tag ${{ steps.release.outputs.tag }}
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
          git push --force --tags "https://$USERNAME:$REPO_KEY@github.com/$GOLANG_EVENTS_REPO" main:main
      - name: Create Release
        if: ${{ success() }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        with:
          tag_name: ${{ steps.release.outputs.tag }}
          release_name: ${{ steps.release.outputs.tag }}
          body: |
            Release ${{ steps.release.outputs.tag }} (auto generated)
          draft: false
          prerelease: false
      - name: Slack Notify
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: "Protobuf Deployment"
          SLACK_MESSAGE: "${{ job.status }} on protobuf deployment for ${{ github.ref_type }}: ${{ github.ref_name }}"
          SLACK_USERNAME: ${{ github.actor }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: event,actions url,commit 
