name: Protobuf Compile
on:
  push:
    branches:
      - '*'
      - '!main'
 
jobs:
  go-image-build:
    uses:  tommzn/github-ci/.github/workflows/go.protobuf.complie.yml@v1.0.21
    secrets:
      cr-pat: ${{ secrets.PUSH_TOKEN }}