name: Protobuf Compile
on:
  push:
    branches:
      - '*'
      - '!main'
 
jobs:
  compile-go:
    uses:  tommzn/github-ci/.github/workflows/go.protobuf.complie.yml@v1.0.47
    secrets:
      cr-pat: ${{ secrets.PUSH_TOKEN }}
      slack-channel: ${{ secrets.SLACK_CHANNEL }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
